export const INJECT_SERVER_PORT = 'INJECT_SERVER_PORT';
export const INJECT_FOXX_MIDDLEWARES = 'INJECT_FOXX_MIDDLEWARES';
export const INJECT_FOXX_DRIVER = 'INJECT_FOXX_DRIVER';
export const INJECT_SRC_DIRS = 'INJECT_SRC_DIRS';
export const INJECT_ROUTES = 'INJECT_ROUTES';
export const INJECT_CATCHERS = 'INJECT_CATCHERS';
export const INJECT_OPEN_API = 'INJECT_OPEN_API';
